"""Sensor-only display names; stable keys and register/control metadata stay unchanged."""

from __future__ import annotations

# Ordering is explicit so new telemetry cannot renumber existing sensor names.
# Binary readbacks use their register key here, while retaining their _readback
# identity in the binary_sensor platform. No writable control uses this catalogue.
SENSOR_NAMES: dict[str, str] = {
    # C1: Climate.
    "effective_inside_temperature": "C1.01 Climate — Inside Temperature (Effective)",
    "effective_outside_temperature": "C1.02 Climate — Outside Temperature (Effective)",
    "inside_relative_humidity": "C1.03 Climate — Inside Humidity",
    "inside_dew_point": "C1.04 Climate — Inside Dew Point",
    "indoor_temperature": "C1.05 Climate — Thermia Inside Temperature",
    "outdoor_temperature": "C1.06 Climate — Thermia Outside Temperature",
    "inside_temperature_source": "C1.07 Climate — Inside Temperature Source",
    "outside_temperature_source": "C1.08 Climate — Outside Temperature Source",
    "outdoor_source": "C1.09 Climate — Thermia Outside Temperature Source",
    "bms_outdoor_temperature": "C1.10 Climate — BMS Outside Temperature",
    "room_sensor_alarm": "C1.11 Climate — Inside Temperature Sensor Alarm",
    "outdoor_sensor_alarm": "C1.12 Climate — Outside Temperature Sensor Alarm",
    # C2: Heating.
    "supply_temperature": "C2.01 Heating — System Supply Temperature",
    "return_temperature": "C2.02 Heating — System Return Temperature",
    "calculated_supply_target": "C2.03 Heating — Calculated Supply Target",
    "heating_excess_time_remaining": "C2.04 Heating — Excess Energy Time Remaining",
    "heating_running": "C2.05 Heating — Running",
    "heating_mode_and_preset": "C2.06 Heating — Mode And Preset",
    "comfort_wheel": "C2.07 Heating — Comfort Wheel Raw Temperature Setting",
    "selected_heat_curve": "C2.08 Heating — Selected Heat Curve",
    "calculated_heat_demand": "C2.09 Heating — Calculated Heat Demand",
    "heating_integral": "C2.10 Heating — Heating Season Integral",
    "buffer_temperature": "C2.11 Heating — Buffer Tank Temperature",
    "buffer_charge_target": "C2.12 Heating — Buffer Tank Charge Target",
    "max_supply_temperature": "C2.13 Heating — Maximum Heating Curve Supply Temperature",
    "min_supply_temperature": "C2.14 Heating — Minimum Heating Curve Supply Temperature",
    "heating_season_stop": "C2.15 Heating — Heating Season Stop Temperature",
    "fixed_supply_target": "C2.16 Heating — Fixed Supply Target",
    "heating_enabled": "C2.17 Heating — Heating Enabled",
    "fixed_supply_enabled": "C2.18 Heating — Fixed Supply Target Enabled",
    "heating_season_active": "C2.19 Heating — Heating Season Active",
    "desired_gear_heating": "C2.20 Heating — Desired Gear For Heating",
    "min_heating_gear": "C2.21 Heating — Minimum Heating Gear",
    "max_heating_gear": "C2.22 Heating — Maximum Heating Gear",
    "gear_shift_delay_heating": "C2.23 Heating — Gear Shift Delay Heating",
    "mix_valve_temperature": "C2.24 Heating — Mix Valve 1 Supply Temperature",
    "mix_valve_position": "C2.25 Heating — Mix Valve 1 Position",
    "mix_valve_target": "C2.26 Heating — Mix Valve 1 Distribution Target",
    "mix_valve_min_supply": "C2.27 Heating — Mix Valve 1 Minimum Supply",
    "mix_valve_max_supply": "C2.28 Heating — Mix Valve 1 Maximum Supply",
    "mix_valve_mode": "C2.29 Heating — Mix Valve 1 Selected Mode",
    "mix_valve_enabled": "C2.30 Heating — Mix Valve 1 Enabled",
    "system_pump_enabled": "C2.31 Heating — System Circulation Pump Enabled",
    "system_pump_signal": "C2.32 Heating — System Circulation Pump Control Signal",
    "mix_valve_pump_signal": "C2.33 Heating — Mix Valve 1 Pump Control Signal",
    "supply_low_alarm": "C2.34 Heating — System Supply Low Temperature Alarm",
    "supply_sensor_alarm": "C2.35 Heating — System Supply Sensor Alarm",
    "mix_valve_sensor_alarm": "C2.36 Heating — Mix Valve 1 Supply Sensor Alarm",
    "mix_valve_deviation_alarm": "C2.37 Heating — Mix Valve 1 Supply Deviation Alarm",
    "heat_curve_outdoor_1": "C2.38 Heating — Heat Curve Outside Point 1",
    "heat_curve_outdoor_2": "C2.39 Heating — Heat Curve Outside Point 2",
    "heat_curve_outdoor_3": "C2.40 Heating — Heat Curve Outside Point 3",
    "heat_curve_outdoor_4": "C2.41 Heating — Heat Curve Outside Point 4",
    "heat_curve_outdoor_5": "C2.42 Heating — Heat Curve Outside Point 5",
    "heat_curve_outdoor_6": "C2.43 Heating — Heat Curve Outside Point 6",
    "heat_curve_outdoor_7": "C2.44 Heating — Heat Curve Outside Point 7",
    "heat_curve_supply_1": "C2.45 Heating — Heat Curve Supply Point 1",
    "heat_curve_supply_2": "C2.46 Heating — Heat Curve Supply Point 2",
    "heat_curve_supply_3": "C2.47 Heating — Heat Curve Supply Point 3",
    "heat_curve_supply_4": "C2.48 Heating — Heat Curve Supply Point 4",
    "heat_curve_supply_5": "C2.49 Heating — Heat Curve Supply Point 5",
    "heat_curve_supply_6": "C2.50 Heating — Heat Curve Supply Point 6",
    "heat_curve_supply_7": "C2.51 Heating — Heat Curve Supply Point 7",
    "mix_valve_curve_supply_1": "C2.52 Heating — Mix Valve 1 Heat Curve Point 1",
    "mix_valve_curve_supply_2": "C2.53 Heating — Mix Valve 1 Heat Curve Point 2",
    "mix_valve_curve_supply_3": "C2.54 Heating — Mix Valve 1 Heat Curve Point 3",
    "mix_valve_curve_supply_4": "C2.55 Heating — Mix Valve 1 Heat Curve Point 4",
    "mix_valve_curve_supply_5": "C2.56 Heating — Mix Valve 1 Heat Curve Point 5",
    "mix_valve_curve_supply_6": "C2.57 Heating — Mix Valve 1 Heat Curve Point 6",
    "mix_valve_curve_supply_7": "C2.58 Heating — Mix Valve 1 Heat Curve Point 7",
    # C3: Hot Water.
    "hot_water_top_temperature": "C3.01 Hot Water — Tank Top Temperature",
    "hot_water_lower_temperature": "C3.02 Hot Water — Tank Lower Temperature",
    "hot_water_weighted_temperature": "C3.03 Hot Water — Tank Weighted Temperature",
    "hot_water_excess_time_remaining": "C3.04 Hot Water — Excess Energy Time Remaining",
    "hot_water_low_time_remaining": "C3.05 Hot Water — Low Mode Time Remaining",
    "hot_water_running": "C3.06 Hot Water — Running",
    "anti_legionella_running": "C3.07 Hot Water — Anti-Legionella Running",
    "hot_water_mode_and_preset": "C3.08 Hot Water — Mode And Preset",
    "hot_water_valve_position": "C3.09 Hot Water — Valve Position",
    "hot_water_operating_hours": "C3.10 Hot Water — Operating Hours",
    "hot_water_start": "C3.11 Hot Water — START Temperature (Readback)",
    "hot_water_stop": "C3.12 Hot Water — STOP Temperature (Readback)",
    "min_hot_water_gear": "C3.13 Hot Water — Minimum Hot Water Gear",
    "max_hot_water_gear": "C3.14 Hot Water — Maximum Hot Water Gear",
    "hot_water_boost": "C3.15 Hot Water — Thermia Boost Request (Readback)",
    "desired_gear_hot_water": "C3.16 Hot Water — Desired Gear For Hot Water",
    "hot_water_enabled": "C3.17 Hot Water — Enabled (Readback)",
    "anti_legionella_enabled": "C3.18 Hot Water — Anti-Legionella Enabled (Readback)",
    "hot_water_mid_sensor_alarm": "C3.19 Hot Water — Hot Water Mid Sensor Alarm",
    "hot_water_top_sensor_alarm": "C3.20 Hot Water — Hot Water Top Sensor Alarm",
    # C4: Cooling.
    "cooling_running": "C4.01 Cooling — Running",
    "cooling_humidity_protection": "C4.02 Cooling — Humidity Protection",
    "cooling_integral": "C4.03 Cooling — Cooling Season Integral",
    "cooling_supply_temperature": "C4.04 Cooling — Cooling Circuit Supply Temperature",
    "cooling_mix_valve_position": "C4.05 Cooling — Cooling Mix Valve Opening",
    "desired_gear_cooling": "C4.06 Cooling — Desired Gear For Cooling",
    "min_cooling_gear": "C4.07 Cooling — Minimum Cooling Gear",
    "max_cooling_gear": "C4.08 Cooling — Maximum Cooling Gear",
    "gear_shift_delay_cooling": "C4.09 Cooling — Gear Shift Delay Cooling",
    "cooling_mix_valve_setting": "C4.10 Cooling — Cooling Mix Valve Set Point",
    "cooling_mix_valve_min": "C4.11 Cooling — Cooling Mix Valve Minimum Opening",
    "cooling_mix_valve_max": "C4.12 Cooling — Cooling Mix Valve Maximum Opening",
    "cooling_start": "C4.13 Cooling — Cooling Start Temperature",
    "cooling_stop": "C4.14 Cooling — Cooling Stop Temperature",
    "passive_cooling_supply_target": "C4.15 Cooling — Passive Cooling Supply Target",
    "minimum_outdoor_for_cooling": "C4.16 Cooling — Minimum Outside Temperature For Cooling",
    "active_cooling_enabled": "C4.17 Cooling — Active Cooling Enabled",
    "passive_cooling_enabled": "C4.18 Cooling — Passive Cooling Enabled",
    "mix_valve_cooling_outdoor_dependent": "C4.19 Cooling — Mix Valve Cooling Outside Dependence",
    "brine_pump_during_cooling": "C4.20 Cooling — Brine Pump During Mix Valve Cooling",
    "cooling_pump_signal": "C4.21 Cooling — Cooling Circulation Pump Control Signal",
    "cooling_regulation_signal": "C4.22 Cooling — Cooling Regulation Control Signal",
    "active_cooling_directional_valve": "C4.23 Cooling — Active Cooling Directional Valve Position",
    "mix_valve_passive_cooling_active": "C4.24 Cooling — Mix Valve 1 Passive Cooling Active",
    "cooling_supply_sensor_alarm": "C4.25 Cooling — Cooling Supply Sensor Alarm",
    "cooling_supply_deviation_alarm": "C4.26 Cooling — Cooling Supply Deviation Alarm",
    # C5: Heat Pump.
    "compressor_speed_rpm": "C5.01 Heat Pump — Compressor Speed",
    "compressor_current_gear": "C5.02 Heat Pump — Compressor Current Gear",
    "brine_in_temperature": "C5.03 Heat Pump — Brine Inlet Temperature",
    "brine_out_temperature": "C5.04 Heat Pump — Brine Outlet Temperature",
    "condenser_pump_speed": "C5.05 Heat Pump — Condenser Circulation Pump Speed",
    "auxiliary_heater_running": "C5.06 Heat Pump — Auxiliary Heater Running",
    "compressor_speed_percent": "C5.07 Heat Pump — Compressor Speed Percentage",
    "compressor_operating_hours": "C5.08 Heat Pump — Compressor Operating Hours",
    "compressor_available_gears": "C5.09 Heat Pump — Compressor Available Gears",
    "start_restriction_timer": "C5.10 Heat Pump — Compressor Start Restriction",
    "compressor_current_hysteresis": "C5.11 Heat Pump — Compressor Current Hysteresis",
    "compressor_signal": "C5.12 Heat Pump — Compressor Control Signal",
    "compressor_speed_limited": "C5.13 Heat Pump — Compressor Unable To Increase Speed",
    "condenser_in_temperature": "C5.14 Heat Pump — Return Temperature (Condenser Inlet)",
    "condenser_out_temperature": "C5.15 Heat Pump — Supply Temperature (Condenser Outlet)",
    "brine_pump_speed": "C5.16 Heat Pump — Brine Circulation Pump Speed",
    "discharge_temperature": "C5.17 Heat Pump — Discharge Pipe Temperature",
    "liquid_line_temperature": "C5.18 Heat Pump — Liquid Line Temperature",
    "suction_gas_temperature": "C5.19 Heat Pump — Suction Gas Temperature",
    "high_pressure_bubble_temperature": "C5.20 Heat Pump — High Pressure Bubble Point",
    "high_pressure_dew_temperature": "C5.21 Heat Pump — High Pressure Dew Point",
    "low_pressure_dew_temperature": "C5.22 Heat Pump — Low Pressure Dew Point",
    "superheat": "C5.23 Heat Pump — Superheat Temperature Difference",
    "subcooling": "C5.24 Heat Pump — Subcooling Temperature Difference",
    "low_pressure": "C5.25 Heat Pump — Low Side Pressure",
    "high_pressure": "C5.26 Heat Pump — High Side Pressure",
    "expansion_valve_opening": "C5.27 Heat Pump — Expansion Valve Opening",
    "inverter_temperature": "C5.28 Heat Pump — Inverter Temperature",
    "immersion_heater_step": "C5.29 Heat Pump — Internal Immersion Heater Active Step",
    "additional_heater_active": "C5.30 Heat Pump — External Additional Heater Active",
    "additional_heater_demand": "C5.31 Heat Pump — External Additional Heater Demand",
    "additional_heater_operating_hours": "C5.32 Heat Pump — External Additional Heater Operating Hours",
    "additional_heater_start": "C5.33 Heat Pump — External Additional Heater Start PID Sum",
    "additional_heater_stop": "C5.34 Heat Pump — External Additional Heater Stop PID Sum",
    "additional_heater_outdoor_limit": "C5.35 Heat Pump — External Heater Outside Temperature Limit",
    "immersion_heater": "C5.36 Heat Pump — Internal Immersion Heater Allowed",
    "additional_heater_enabled": "C5.37 Heat Pump — External Additional Heater Enabled",
    "additional_heater_only": "C5.38 Heat Pump — Additional Heater Only Operation",
    "additional_heater_outdoor_dependent": "C5.39 Heat Pump — External Heater Outside Dependence",
    "additional_heater_signal": "C5.40 Heat Pump — External Additional Heater Control Signal",
    "external_heater_pump_signal": "C5.41 Heat Pump — External Heater Pump Control Signal",
    "condenser_pump_min_speed": "C5.42 Heat Pump — Condenser Pump Minimum Speed",
    "condenser_pump_max_speed": "C5.43 Heat Pump — Condenser Pump Maximum Speed",
    "condenser_pump_standby_speed": "C5.44 Heat Pump — Condenser Pump Standby Speed",
    "brine_pump_min_speed": "C5.45 Heat Pump — Brine Pump Minimum Speed",
    "brine_pump_max_speed": "C5.46 Heat Pump — Brine Pump Maximum Speed",
    "brine_pump_standby_speed": "C5.47 Heat Pump — Brine Pump Standby Speed",
    "condenser_pump_variable_speed": "C5.48 Heat Pump — Condenser Pump Variable Speed Enabled",
    "condenser_pump_continuous": "C5.49 Heat Pump — Condenser Pump Continuous Operation",
    "condenser_pump_signal": "C5.50 Heat Pump — Condenser Pump Control Signal",
    "brine_pump_variable_speed": "C5.51 Heat Pump — Brine Pump Variable Speed Enabled",
    "brine_pump_continuous": "C5.52 Heat Pump — Brine Pump Continuous Operation",
    "brine_pump_signal": "C5.53 Heat Pump — Brine Pump Control Signal",
    "brine_external_start": "C5.54 Heat Pump — External Brine Pump Start Input",
    "ground_water_relay_active": "C5.55 Heat Pump — Brine Or Ground Water External Relay",
    "brine_in_high_limit": "C5.56 Heat Pump — Brine Inlet High Alarm Limit",
    "brine_in_low_limit": "C5.57 Heat Pump — Brine Inlet Low Alarm Limit",
    "brine_out_low_limit": "C5.58 Heat Pump — Brine Outlet Low Alarm Limit",
    "brine_max_delta": "C5.59 Heat Pump — Brine Maximum Temperature Difference",
    "brine_in_monitoring_enabled": "C5.60 Heat Pump — Brine Inlet Monitoring Enabled",
    "brine_out_monitoring_enabled": "C5.61 Heat Pump — Brine Outlet Monitoring Enabled",
    "flow_switch_enabled": "C5.62 Heat Pump — Flow Or Pressure Switch Enabled",
    "evaporator_freeze_protection": "C5.63 Heat Pump — Evaporator Freeze Protection Enabled",
    "high_pressure_alarm": "C5.64 Heat Pump — High Pressure Switch Alarm",
    "low_pressure_alarm": "C5.65 Heat Pump — Low Pressure Level Alarm",
    "discharge_high_alarm": "C5.66 Heat Pump — High Discharge Temperature Alarm",
    "pressure_limit_active": "C5.67 Heat Pump — Operating Pressure Limit Active",
    "discharge_sensor_alarm": "C5.68 Heat Pump — Discharge Pipe Sensor Alarm",
    "liquid_sensor_alarm": "C5.69 Heat Pump — Liquid Line Sensor Alarm",
    "suction_sensor_alarm": "C5.70 Heat Pump — Suction Gas Sensor Alarm",
    "flow_switch_alarm": "C5.71 Heat Pump — Flow Or Pressure Switch Alarm",
    "inverter_alarm": "C5.72 Heat Pump — Inverter Alarm",
    "compressor_low_speed_alarm": "C5.73 Heat Pump — Compressor Low Speed Alarm",
    "low_superheat_alarm": "C5.74 Heat Pump — Low Superheat Alarm",
    "pressure_ratio_alarm": "C5.75 Heat Pump — Pressure Ratio Out Of Range Alarm",
    "compressor_envelope_alarm": "C5.76 Heat Pump — Compressor Pressure Envelope Alarm",
    "brine_temperature_alarm": "C5.77 Heat Pump — Brine Temperature Out Of Range Alarm",
    "brine_in_sensor_alarm": "C5.78 Heat Pump — Brine Inlet Sensor Alarm",
    "brine_out_sensor_alarm": "C5.79 Heat Pump — Brine Outlet Sensor Alarm",
    "condenser_in_sensor_alarm": "C5.80 Heat Pump — Condenser Inlet Sensor Alarm",
    "condenser_out_sensor_alarm": "C5.81 Heat Pump — Condenser Outlet Sensor Alarm",
    "brine_delta_alarm": "C5.82 Heat Pump — Brine Temperature Difference Alarm",
    "brine_in_high_alarm": "C5.83 Heat Pump — Brine Inlet High Temperature Alarm",
    "brine_in_low_alarm": "C5.84 Heat Pump — Brine Inlet Low Temperature Alarm",
    "brine_out_low_alarm": "C5.85 Heat Pump — Brine Outlet Low Temperature Alarm",
    "inverter_communication_alarm": "C5.86 Heat Pump — Inverter Communication Alarm",
    "oil_boost_active": "C5.87 Heat Pump — Oil Boost In Progress",
    "heat_pump_stopping": "C5.88 Heat Pump — Heat Pump Stopping",
    "heat_pump_ok_to_start": "C5.89 Heat Pump — Heat Pump Ready To Start",
    # C6: Energy.
    "electric_power": "C6.01 Energy — Electrical Power",
    "thermal_power": "C6.02 Energy — Thermal Power",
    "instantaneous_cop": "C6.03 Energy — Instantaneous COP",
    "meter_current_l1": "C6.04 Energy — Electric Meter L1 Current",
    "meter_current_l2": "C6.05 Energy — Electric Meter L2 Current",
    "meter_current_l3": "C6.06 Energy — Electric Meter L3 Current",
    "meter_voltage_l1_neutral": "C6.07 Energy — Electric Meter L1 To Neutral Voltage",
    "meter_voltage_l2_neutral": "C6.08 Energy — Electric Meter L2 To Neutral Voltage",
    "meter_voltage_l3_neutral": "C6.09 Energy — Electric Meter L3 To Neutral Voltage",
    "meter_voltage_l1_l2": "C6.10 Energy — Electric Meter L1 To L2 Voltage",
    "meter_voltage_l2_l3": "C6.11 Energy — Electric Meter L2 To L3 Voltage",
    "meter_voltage_l3_l1": "C6.12 Energy — Electric Meter L3 To L1 Voltage",
    "meter_power_l1": "C6.13 Energy — Electric Meter L1 Power",
    "meter_power_l2": "C6.14 Energy — Electric Meter L2 Power",
    "meter_power_l3": "C6.15 Energy — Electric Meter L3 Power",
    "meter_energy": "C6.16 Energy — Electric Meter Total Energy",
    "meter_energy_integer": "C6.17 Energy — Electric Meter Energy (Whole kWh)",
    "smart_grid_status": "C6.18 Energy — Current Smart Grid Mode",
    "smart_grid_request": "C6.19 Energy — Desired Power Consumption Control",
    "smart_grid_input_1": "C6.20 Energy — Smart Grid Input 1",
    "smart_grid_input_2": "C6.21 Energy — Smart Grid Input 2",
    "input_power_limit": "C6.22 Energy — Input Power Limit",
    "max_phase_current": "C6.23 Energy — Maximum Phase Current",
    "current_limitation_enabled": "C6.24 Energy — Current Limitation Enabled",
    "current_limit_external_heater": "C6.25 Energy — Current Limiter Restricts External Heater",
    "current_limit_secondaries": "C6.26 Energy — Current Limiter Restricts Secondary Units",
    "phase_detection_alarm": "C6.27 Energy — Power Phase Detection Alarm",
    # C7: System.
    "main_demand": "C7.01 System — Operating Status",
    "control_warning": "C7.02 System — Control Status",
    "control_logic": "C7.03 System — Control Logic",
    "active_demand_flags": "C7.04 System — Active Demand Flags",
    "second_demand": "C7.05 System — Second Running Demand",
    "third_demand": "C7.06 System — Third Running Demand",
    "queued_demand_1": "C7.07 System — Queued Demand 1",
    "queued_demand_2": "C7.08 System — Queued Demand 2",
    "queued_demand_3": "C7.09 System — Queued Demand 3",
    "queued_demand_4": "C7.10 System — Queued Demand 4",
    "queued_demand_5": "C7.11 System — Queued Demand 5",
    "operational_mode": "C7.12 System — Operational Mode Setting",
    "available_secondaries": "C7.13 System — Available Genesis Secondary Units",
    "distributed_gears": "C7.14 System — Total Distributed Gears",
    "maximum_requested_gear": "C7.15 System — Maximum Requested Gear",
    "software_major": "C7.16 System — Control Software Major Version",
    "software_minor": "C7.17 System — Control Software Minor Version",
    "software_micro": "C7.18 System — Control Software Micro Version",
    "alarm_class_a": "C7.19 System — Class A Alarm",
    "alarm_class_b": "C7.20 System — Class B Alarm",
    "alarm_class_c": "C7.21 System — Class C Alarm",
    "alarm_class_d": "C7.22 System — Class D Secondary Alarm",
    "sum_alarm": "C7.23 System — Sum Alarm",
    "alarm_reset": "C7.24 System — Alarm Reset Control",
    "external_alarm": "C7.25 System — External Alarm Input",
    "secondary_class_d_flags": "C7.26 System — Secondary Class D Alarm Flags",
    "secondary_communication_flags": "C7.27 System — Secondary Communication Alarm Flags",
    "secondary_class_a_flags": "C7.28 System — Secondary Class A Alarm Flags",
    "secondary_class_b_flags": "C7.29 System — Secondary Class B Alarm Flags",
    "secondary_unit_alarm": "C7.30 System — Secondary Unit Communication Alarm",
    "primary_conflict_alarm": "C7.31 System — Primary Unit Network Conflict Alarm",
    "primary_missing_secondary_alarm": "C7.32 System — Primary Unit Missing Secondary Alarm",
    "pool_enabled": "C7.33 System — Pool Enabled",
    "pool_additional_heater_enabled": "C7.34 System — External Heater For Pool Enabled",
    "pool_charge_setting": "C7.35 System — Pool Charge Set Point",
    "pool_return_target": "C7.36 System — Pool Return Temperature Target",
    "pool_hysteresis": "C7.37 System — Pool Hysteresis",
    "min_pool_gear": "C7.38 System — Minimum Pool Gear",
    "max_pool_gear": "C7.39 System — Maximum Pool Gear",
    "desired_gear_pool": "C7.40 System — Desired Gear For Pool",
    "gear_shift_delay_pool": "C7.41 System — Gear Shift Delay Pool",
    "pool_sensor_alarm": "C7.42 System — Pool Return Sensor Alarm",
    "pool_external_stop": "C7.43 System — Pool External Stop",
    "pool_directional_valve": "C7.44 System — Pool Directional Valve Position",
    "surplus_heat_directional_valve": "C7.45 System — Surplus Heat Directional Valve Position",
}


def sensor_name(key: str) -> str:
    """Look up the display label without changing the entity identity."""
    return SENSOR_NAMES[key]
